// generated by xgen -- DO NOT EDIT
package user

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var roleCtl = &RoleController{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "sys",
			Module:  "user.role",
			Title:   "用户角色",
		},
		Mgr: RoleMgr,
	},
}

type RoleController struct {
	controller.JSONController
}
