// generated by xgen -- DO NOT EDIT
package issue

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var ctl = &Controller{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "store",
			Module:  "issue",
			Title:   "小程序发布",
		},
		Mgr: Mgr,
	},
}

type Controller struct {
	controller.JSONController
}
