// generated by xgen -- DO NOT EDIT
package release

import (
	"gopkg.in/goyy/goyy.v0/web/controller"
)

var ctl = &Controller{
	JSONController: controller.JSONController{
		Settings: controller.Settings{
			Project: "store",
			Module:  "release",
			Title:   "商店发布",
		},
		Mgr: Mgr,
	},
}

type Controller struct {
	controller.JSONController
}
